# Generated by Django 5.0.2 on 2024-02-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000)),
                ('desc', models.CharField(max_length=10000)),
                ('image', models.ImageField(upload_to='project/media')),
                ('skil', models.CharField(max_length=100)),
                ('githubLinkFrontend', models.CharField(max_length=100)),
                ('githubLinkBAckend', models.CharField(max_length=1000)),
                ('backendLink', models.CharField(max_length=1000)),
                ('frontendLink', models.CharField(max_length=1000)),
            ],
        ),
    ]
