# Generated by Django 5.0.2 on 2024-02-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_skil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=500)),
                ('message', models.TextField()),
            ],
        ),
    ]
